# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2711ce20e94dc30342612143a75a957e5bd55de76222e32759819674e02ca004a25e5ecaa1f936d88579fc0922d6acb0ae7169f7aa71db3647dd77d802c7052

test:
  secret_key_base: e4069c622b0c04a778a6002cdc351a039bda52ed81c93563eeec45dacf442137024fefcdb6863dd833c94badafb03c548b0e14bed853fb5a9a9bed1b0dc36a44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
